export interface FemParam {
  desc: string;
  itemid: string;
  /** 需要附加参数（如电磁力幅值 pr(order,freq)） */
  kind?: "pr";
}

export const femCurrentSourceParams: FemParam[] = [
  { desc: "电磁力幅值", itemid: "pr", kind: "pr" },
  { desc: "电磁转矩平均值", itemid: "Tav" },
  { desc: "转矩波动率", itemid: "Tripple" },
  { desc: "定子铁耗", itemid: "PfeSAvg" },
  { desc: "转子铁耗", itemid: "PfeRAvg" },
  { desc: "磁钢涡流损耗", itemid: "PeddyMagAvg" },
  { desc: "D轴电流", itemid: "Id" },
  { desc: "Q轴电流", itemid: "Iq" },
  { desc: "D轴电感", itemid: "Ld" },
  { desc: "Q轴电感", itemid: "Lq" },
  { desc: "A相磁链", itemid: "FLA" },
  { desc: "B相磁链", itemid: "FLB" },
  { desc: "C相磁链", itemid: "FLC" },
  { desc: "电磁功率", itemid: "Pem" },
  { desc: "A相电压有效值", itemid: "Ua" },
  { desc: "B相电压有效值", itemid: "Ub" },
  { desc: "C相电压有效值", itemid: "Uc" },
  { desc: "A相电流有效值", itemid: "Ia" },
  { desc: "B相电流有效值", itemid: "Ib" },
  { desc: "C相电流有效值", itemid: "Ic" },
  { desc: "A相铜耗", itemid: "Pcua" },
  { desc: "B相铜耗", itemid: "Pcub" },
  { desc: "C相铜耗", itemid: "Pcuc" },
  { desc: "线电压", itemid: "Uline" },
  { desc: "线电压谐波畸变率", itemid: "UlineTHD" },
  { desc: "视在功率", itemid: "Pa" },
  { desc: "输出功率", itemid: "P2" },
  { desc: "输入功率", itemid: "P1" },
  { desc: "效率", itemid: "eta" },
  { desc: "铁耗电流", itemid: "Ife" },
  { desc: "修正前功率因数", itemid: "cosphi0" },
  { desc: "修正前电流有效值", itemid: "Irms0" },
  { desc: "修正电流有效值", itemid: "Irms" },
  { desc: "输出转矩", itemid: "T2" },
  { desc: "修正功率因数", itemid: "cosphi" },
  { desc: "线反电势有效值", itemid: "E0rms" },
  { desc: "线反电势谐波畸变率", itemid: "E0THD" },
];

export const femVoltageSourceParams: FemParam[] = [
  { desc: "电磁转矩平均值", itemid: "Tav" },
  { desc: "转矩波动率", itemid: "Tripple" },
  { desc: "定子铁耗", itemid: "PfeSAvg" },
  { desc: "转子铁耗", itemid: "PfeRAvg" },
  { desc: "磁钢涡流损耗", itemid: "PeddyMagAvg" },
  { desc: "D轴电流", itemid: "Id" },
  { desc: "Q轴电流", itemid: "Iq" },
  { desc: "D轴电感", itemid: "Ld" },
  { desc: "Q轴电感", itemid: "Lq" },
  { desc: "A相磁链", itemid: "FLA" },
  { desc: "B相磁链", itemid: "FLB" },
  { desc: "C相磁链", itemid: "FLC" },
  { desc: "电磁功率", itemid: "Pem" },
  { desc: "A相电压有效值", itemid: "Ua" },
  { desc: "B相电压有效值", itemid: "Ub" },
  { desc: "C相电压有效值", itemid: "Uc" },
  { desc: "A相电流有效值", itemid: "Ia" },
  { desc: "B相电流有效值", itemid: "Ib" },
  { desc: "C相电流有效值", itemid: "Ic" },
  { desc: "A相铜耗", itemid: "Pcua" },
  { desc: "B相铜耗", itemid: "Pcub" },
  { desc: "C相铜耗", itemid: "Pcuc" },
  { desc: "视在功率", itemid: "Pa" },
  { desc: "输出功率", itemid: "P2" },
  { desc: "输入功率", itemid: "P1" },
  { desc: "效率", itemid: "eta" },
  { desc: "功率因数", itemid: "cosphi" },
  { desc: "输出转矩", itemid: "T2" },
  { desc: "线反电势有效值", itemid: "E0rms" },
  { desc: "线反电势谐波畸变率", itemid: "E0THD" },
];
