export interface ParamItem {
  desc: string;
  itemid: string;
}
export interface ParamGroup {
  groupdesc: string;
  itemlist: ParamItem[];
}

export const magneticParamGroups: ParamGroup[] = [
  { groupdesc: "基本参数", itemlist: [
    { desc: "电机型号", itemid: "_s_model" },
    { desc: "极数", itemid: "i_pole" },
    { desc: "相数", itemid: "i_phase" },
    { desc: "转子位置", itemid: "er_position" },
    { desc: "效率设计值", itemid: "K_eff" },
    { desc: "功率因数设计值", itemid: "Kpf_design" },
    { desc: "风摩损耗", itemid: "P_wind_friction" },
    { desc: "激励类型", itemid: "e_control" },
    { desc: "计算方式", itemid: "e_solveType" },
    { desc: "控制算法", itemid: "e_algorithm_control" },
    { desc: "电路类型", itemid: "e_circuit" },
    { desc: "直流额定电压", itemid: "U_bus" },
    { desc: "开关管压降", itemid: "U_drop_transistor" },
    { desc: "二极管压降", itemid: "U_drop_diode" },
    { desc: "调制比", itemid: "r_modulate" },
    { desc: "载波比", itemid: "r_carrier" },
    { desc: "正弦波电压", itemid: "U_line" },
    { desc: "正弦波频率", itemid: "f" },
    { desc: "限幅电流", itemid: "I_limiter" },
    { desc: "调制方式", itemid: "e_Modulation_Mode" },
  ]},
  { groupdesc: "电机工况参数", itemlist: [
    { desc: "输出功率", itemid: "P_output" },
    { desc: "工作温度", itemid: "T_work" },
    { desc: "工况类型", itemid: "e_ratedType" },
    { desc: "负载转矩", itemid: "M_load" },
    { desc: "运行转速", itemid: "n_run" },
  ]},
  { groupdesc: "定子铁芯", itemlist: [
    { desc: "定子冲片形状", itemid: "es_shape" },
    { desc: "定子外径", itemid: "Ds_outer" },
    { desc: "切边宽度", itemid: "Ds_cut" },
    { desc: "定子内径", itemid: "Ds_inner" },
    { desc: "铁芯长度", itemid: "lfe" },
    { desc: "铁芯叠压系数", itemid: "Kfe_stacking" },
    { desc: "定子材料名称", itemid: "ss_material" },
    { desc: "定子槽数", itemid: "iss" },
    { desc: "定子斜槽宽度(定子齿距)", itemid: "bss_skew" },
    { desc: "定子槽形", itemid: "ess" },
    { desc: "平行齿", itemid: "ess_tooth" },
    { desc: "齿宽", itemid: "bss_tooth" },
    { desc: "定子槽尺寸b0", itemid: "b01_sslot" },
    { desc: "定子槽尺寸b1", itemid: "bs1_sslot" },
    { desc: "定子槽尺寸b2", itemid: "bs2_sslot" },
    { desc: "定子槽尺寸r", itemid: "rs_sslot" },
    { desc: "定子槽尺寸h0", itemid: "hs0_sslot" },
    { desc: "定子槽尺寸h1", itemid: "hs1_sslot" },
    { desc: "定子槽尺寸h2", itemid: "hs2_sslot" },
    { desc: "定子槽尺寸alpha", itemid: "alpha_sslot" },
  ]},
  { groupdesc: "定子绕组", itemlist: [
    { desc: "定子绕组形式", itemid: "e_winding" },
    { desc: "绕组层数", itemid: "isw_layer" },
    { desc: "相带形式", itemid: "e_phaseband" },
    { desc: "节距（槽数）", itemid: "Y" },
    { desc: "并联支路数", itemid: "i_par_branch" },
    { desc: "每槽导体数", itemid: "i_cond_per_slot" },
    { desc: "绕组线型", itemid: "esw_type" },
    { desc: "第一种导线并绕根数", itemid: "isw_pr" },
    { desc: "圆线第一种线规裸线直径", itemid: "Dsw" },
    { desc: "圆线第一种线规绝缘后直径", itemid: "Dsw_insulated" },
    { desc: "扁线第一种线规导线高度", itemid: "asw" },
    { desc: "扁线第一种线规导线宽度", itemid: "bsw" },
    { desc: "扁线第一种线规绝缘后高度", itemid: "asw_insulated" },
    { desc: "扁线第一种线规绝缘后宽度", itemid: "bsw_insulated" },
    { desc: "第二种导线并绕根数", itemid: "isw_pr2" },
    { desc: "圆线第二种线规裸线直径", itemid: "Dsw2" },
    { desc: "圆线第二种线规绝缘后直径", itemid: "Dsw2_insulated" },
    { desc: "扁线第二种线规导线高度", itemid: "asw2" },
    { desc: "扁线第二种线规导线宽度", itemid: "bsw2" },
    { desc: "扁线第二种线规绝缘后高度", itemid: "asw2_insulated" },
    { desc: "扁线第二种线规绝缘后宽度", itemid: "bsw2_insulated" },
    { desc: "定子线圈端部类型", itemid: "esw_end_style" },
    { desc: "定子绕组直线部分伸出铁芯长度", itemid: "lsw_end_adjust" },
    { desc: "定子绕组端部高度(轴向投影长度)", itemid: "hsw_end_height" },
    { desc: "定子线圈平均半匝长度", itemid: "l_ht_av" },
    { desc: "定子槽绝缘厚度", itemid: "hss_insulated" },
    { desc: "层间绝缘厚度", itemid: "hss_layer_insulated" },
    { desc: "槽底绝缘厚度", itemid: "hss_btm_insulated" },
    { desc: "线圈绝缘厚度", itemid: "hss_coil_insulated" },
    { desc: "槽楔厚度", itemid: "h_wedge" },
    { desc: "定子绕组的导线材料", itemid: "esw_wire_material" },
    { desc: "定子槽满率", itemid: "r_sf" },
  ]},
  { groupdesc: "转子磁极参数", itemlist: [
    { desc: "转子类型", itemid: "er" },
    { desc: "转子磁极中心气隙", itemid: "lg" },
    { desc: "转子外径", itemid: "Drf_outer" },
    { desc: "转子内径", itemid: "Drf_inner" },
    { desc: "转轴直径", itemid: "Dsh" },
    { desc: "转子铁芯长度", itemid: "lrf" },
    { desc: "转子铁芯材料", itemid: "srf_material" },
    { desc: "转子铁芯叠压系数", itemid: "Krf_stacking" },
    { desc: "极弧偏心距", itemid: "ypa_offset" },
    { desc: "极弧系数", itemid: "Kpa" },
    { desc: "磁钢材料", itemid: "sm_material" },
    { desc: "磁钢厚度", itemid: "hm" },
    { desc: "削角厚度", itemid: "hm_chamfer" },
    { desc: "削角角度", itemid: "Am_chamfer" },
    { desc: "磁钢宽度", itemid: "bm" },
    { desc: "磁钢轴向长度", itemid: "lm" },
    { desc: "肋宽", itemid: "bm_rib" },
    { desc: "磁桥厚度", itemid: "hm_bridge" },
    { desc: "磁钢内侧半径R", itemid: "rm_outer" },
    { desc: "倒角半径", itemid: "rm_fillet" },
    { desc: "定位长度L", itemid: "lm_locate" },
    { desc: "残隙", itemid: "lg_rest" },
  ]},
  { groupdesc: "转轴参数", itemlist: [
    { desc: "轴材料", itemid: "ssh_material" },
  ]},
  { groupdesc: "磁钢数据（工作温度下）", itemlist: [
    { desc: "剩磁密度", itemid: "Bm_Br" },
    { desc: "矫顽力", itemid: "Hm_Hc" },
    { desc: "相对回复磁导率", itemid: "r_mur" },
  ]},
  { groupdesc: "材料消耗", itemlist: [
    { desc: "铜密度", itemid: "msw_wire" },
    { desc: "电枢铜量", itemid: "Gsw" },
    { desc: "电枢铜的价格", itemid: "Jsw" },
    { desc: "定子铁芯密度", itemid: "msf" },
    { desc: "定子铁芯重量", itemid: "Gsf" },
    { desc: "转子铁芯密度", itemid: "mrf" },
    { desc: "转子铁重", itemid: "Grf" },
    { desc: "铁芯耗材", itemid: "Gf" },
    { desc: "铁芯价格", itemid: "Jf" },
    { desc: "磁钢密度", itemid: "mm" },
    { desc: "磁钢重量", itemid: "Gm" },
    { desc: "磁钢价格", itemid: "Jm" },
    { desc: "总净重", itemid: "Gtotal" },
  ]},
  { groupdesc: "稳态参数", itemlist: [
    { desc: "定子绕组系数", itemid: "kw" },
    { desc: "直轴电枢反应电抗", itemid: "Xad" },
    { desc: "交轴电枢反应电抗", itemid: "Xaq" },
    { desc: "直轴同步电抗", itemid: "Xd" },
    { desc: "交轴同步电抗", itemid: "Xq" },
    { desc: "直轴同步电感", itemid: "Ld" },
    { desc: "交轴同步电感", itemid: "Lq" },
    { desc: "电枢反应电抗", itemid: "Xa" },
    { desc: "电枢反应电感", itemid: "La" },
    { desc: "同步电抗", itemid: "Xc" },
    { desc: "电枢绕组相电阻", itemid: "R1" },
    { desc: "电枢绕组漏电抗", itemid: "X1" },
  ]},
  { groupdesc: "空载磁路数据", itemlist: [
    { desc: "空载工作点", itemid: "bm0" },
    { desc: "定子齿部磁通密度", itemid: "Bst" },
    { desc: "定子轭部磁通密度", itemid: "Bsy" },
    { desc: "转子轭部磁通密度", itemid: "Bry" },
    { desc: "转子齿部磁通密度", itemid: "Brt" },
    { desc: "气隙磁密", itemid: "Bg" },
    { desc: "定子齿磁势", itemid: "Fst" },
    { desc: "定子轭磁势", itemid: "Fsy" },
    { desc: "转子轭部磁势", itemid: "Fry" },
    { desc: "定子轭磁势", itemid: "Frt" },
    { desc: "气隙磁势", itemid: "Fg" },
    { desc: "外磁路总磁势", itemid: "F_total" },
    { desc: "饱和系数", itemid: "Ks" },
    { desc: "漏磁系数", itemid: "Klf" },
    { desc: "定子轭部磁路长修正系数", itemid: "Ksy_ml_adjust" },
    { desc: "线电压", itemid: "U_l" },
    { desc: "线反电势", itemid: "Uiv_effi_line" },
  ]},
  { groupdesc: "满载数据", itemlist: [
    { desc: "电机线电流有效值", itemid: "I_line" },
    { desc: "电机相电流有效值", itemid: "I_phase" },
    { desc: "d轴电流", itemid: "Id" },
    { desc: "q轴电流", itemid: "Iq" },
    { desc: "电枢线负荷", itemid: "LLs" },
    { desc: "电枢热负荷", itemid: "TLs" },
    { desc: "电枢电流密度", itemid: "IDsw" },
    { desc: "相电压", itemid: "U_phase" },
    { desc: "线电压", itemid: "UL" },
    { desc: "摩擦损耗", itemid: "Pwf" },
    { desc: "定子齿部铁耗", itemid: "Ptfe" },
    { desc: "定子轭部铁耗", itemid: "Pjfe" },
    { desc: "铁芯损耗", itemid: "Pfe" },
    { desc: "定子槽部铜耗", itemid: "Pcuc" },
    { desc: "定子端部铜耗", itemid: "Pcud" },
    { desc: "电枢铜耗", itemid: "Pcu" },
    { desc: "开关管损耗", itemid: "P_transistor" },
    { desc: "杂散损耗", itemid: "Ps" },
    { desc: "总损耗", itemid: "P_total" },
    { desc: "输入功率", itemid: "P_input" },
    { desc: "输出功率", itemid: "P2" },
    { desc: "效率", itemid: "Kef" },
    { desc: "功率因数", itemid: "Kpf" },
    { desc: "力矩角", itemid: "A_power" },
    { desc: "同步转速", itemid: "n_sync" },
    { desc: "输出转矩", itemid: "M_output" },
    { desc: "永磁体负载工作点", itemid: "bmN" },
    { desc: "失步转矩倍数", itemid: "Tsb" },
  ]},
  { groupdesc: "最大输出功率时性能数据", itemlist: [
    { desc: "最大功率时电机线电流有效值", itemid: "I_line_p2max" },
    { desc: "最大功率时电机相电流有效值", itemid: "I_phase_p2max" },
    { desc: "最大功率时d轴电流", itemid: "Id_p2max" },
    { desc: "最大功率时q轴电流", itemid: "Iq_p2max" },
    { desc: "最大功率时相电压", itemid: "U_phase_p2max" },
    { desc: "最大功率时线电压", itemid: "U_line_p2max" },
    { desc: "最大功率时摩擦损耗", itemid: "Pwf_p2max" },
    { desc: "最大功率时铁芯损耗", itemid: "Pfe_p2max" },
    { desc: "最大功率时电枢铜耗", itemid: "Pcu_p2max" },
    { desc: "最大功率时杂散损耗", itemid: "Ps_p2max" },
    { desc: "最大功率时电磁功率", itemid: "Pem_p2max" },
    { desc: "最大功率时输入功率", itemid: "P_input_p2max" },
    { desc: "最大功率时输出功率", itemid: "P2_p2max" },
    { desc: "最大功率时效率", itemid: "Kef_p2max" },
    { desc: "最大功率时功率因数", itemid: "Kpf_p2max" },
    { desc: "最大功率时同步转速", itemid: "n_sync_p2max" },
    { desc: "最大功率时输出转矩", itemid: "M_output_p2max" },
    { desc: "最大功率时电磁转矩", itemid: "Tem_p2max" },
  ]},
];
